// src/components/FileDownload.tsx
/**
 * @file File download component
 */

// Imports
import {type Component, createMemo, JSXElement, Show} from "solid-js";

interface FileDownloadProps {
  label: string;
  leading?: JSXElement;
  trailing?: JSXElement;
  filename: string;
  value: Blob;
}

const FileDownload: Component<FileDownloadProps> = props => {
  const href = createMemo(() => URL.createObjectURL(props.value));

  return (
    <a
      class="border-1 centered-row cursor-pointer dark-within:focus:text-gray-500 flex-1 focus-within:text-gray-400 p-2 rounded-md"
      href={href()}
      download={props.filename}
      target="_blank"
    >
      <Show when={props.leading !== undefined}>{props.leading}</Show>

      <span
        classList={{
          "ml-2": props.leading !== undefined,
          "mr-2": props.trailing !== undefined,
        }}
      >
        {props.label}
      </span>

      <Show when={props.trailing !== undefined}>{props.trailing}</Show>
    </a>
  );
};

export default FileDownload;

// src/components/file-download.vue
<script setup lang="ts">
import {computed} from "vue";

// Props
const {value} = defineProps<{
  filename: string;
  label: string;
  value: Blob;
}>();

// Computed
const href = computed(() => URL.createObjectURL(value));
</script>

<template>
  <a
    class="border-1 centered-row cursor-pointer dark-within:focus:text-gray-500 flex-1 focus-within:text-gray-400 p-2 rounded-md"
    :download="filename"
    :href="href"
    target="_blank"
  >
    <slot name="leading" />

    <span
      :class="{
        'ml-2': $slots.leading !== undefined,
        'mr-2': $slots.trailing !== undefined,
      }"
    >
      {{ label }}
    </span>

    <slot name="trailing" />
  </a>
</template>
