// src/components/shortcut.vue
<script setup lang="ts">
import {makeDraggable} from "@vue-dnd-kit/core";
import {useTemplateRef} from "vue";
import {ShortcutLinkHint, type ShortcutMetadata} from "~/lib/types";

// Props
const {metadata, onEdit} = defineProps<{
  metadata: ShortcutMetadata;
  onEdit: () => void;
}>();

// Refs
const parent = useTemplateRef<HTMLElement>("parent");

// Composables
const {} = makeDraggable(parent, {});

// Methods
/**
 * Handle context menu event
 * @param event The context menu event
 */
const onContextMenu = (event: MouseEvent) => {
  event.preventDefault();
  onEdit();
};
</script>

<template>
  <div ref="parent">
    <a
      class="centered-col rounded-xl m-4 p-1"
      :href="metadata.link"
      rel="noopener noreferrer"
      @contextmenu="onContextMenu"
    >
      <img
        :alt="`${metadata.title} icon`"
        class="h-[14vh] w-[14vh] object-contain"
        :src="metadata.icon"
      />
      <h1 class="text-lg">{{ metadata.title }}</h1>
    </a>

    <link
      v-if="metadata.linkHint !== ShortcutLinkHint.NONE"
      :href="metadata.link"
      :rel="metadata.linkHint"
    />
  </div>
</template>

// src/components/Shortcut.tsx
/**
 * @file Shortcut component
 */

// Imports
import {Show} from "solid-js";

import {ShortcutLinkHint, ShortcutMetadata} from "~/lib/types";

interface ShortcutProps {
  metadata: ShortcutMetadata;
  onEdit: () => void;
}

const Shortcut = (props: ShortcutProps) => {
  const onContextMenu = (event: MouseEvent) => {
    event.preventDefault();
    props.onEdit();
  };

  return (
    <div>
      <a
        class="centered-col rounded-xl m-4 p-1"
        href={props.metadata.link}
        rel="noopener noreferrer"
        onContextMenu={onContextMenu}
      >
        <img
          alt={`${props.metadata.title} icon`}
          class="h-[14vh] w-[14vh] object-contain"
          src={props.metadata.icon}
        />
        <h1 class="text-lg">{props.metadata.title}</h1>
      </a>

      <Show when={props.metadata.linkHint !== ShortcutLinkHint.NONE}>
        <link rel={props.metadata.linkHint} href={props.metadata.link} />
      </Show>
    </div>
  );
};

export default Shortcut;
