// src/components/submit-button.vue
<script setup lang="ts">
import {inject} from "vue";
import {FormFieldIdKey} from "~/components/form-field.vue";

// Props
defineProps<{
  label: string;
}>();

// Context
const id = inject(FormFieldIdKey, undefined);
</script>

<template>
  <label
    class="border-1 centered-row cursor-pointer dark-within:focus:text-gray-500 focus-within:text-gray-400 my-2 p-2 rounded-md w-full"
  >
    <slot name="leading" />

    <span
      :class="{
        'ml-2': $slots.leading !== undefined,
        'mr-2': $slots.trailing !== undefined,
      }"
    >
      {{ label }}
    </span>

    <input class="h-0 w-0" :id="id" type="submit" />

    <slot name="trailing" />
  </label>
</template>

// src/components/SubmitButton.tsx
/**
 * @file Submit button component
 */

// Imports
import {type Component, JSXElement, Show, useContext} from "solid-js";

import {FormFieldIdContext} from "~/components/FormField";

interface SubmitButtonProps {
  label: string;
  leading?: JSXElement;
  trailing?: JSXElement;
}

const SubmitButton: Component<SubmitButtonProps> = props => {
  const id = useContext(FormFieldIdContext);

  return (
    <label class="border-1 centered-row cursor-pointer dark-within:focus:text-gray-500 focus-within:text-gray-400 my-2 p-2 rounded-md w-full">
      <Show when={props.leading !== undefined}>{props.leading}</Show>

      <span
        classList={{
          "ml-2": props.leading !== undefined,
          "mr-2": props.trailing !== undefined,
        }}
      >
        {props.label}
      </span>

      <input class="h-0 w-0" id={id} type="submit" />

      <Show when={props.trailing !== undefined}>{props.trailing}</Show>
    </label>
  );
};

export default SubmitButton;
