// src/components/text-box.vue
<script setup lang="ts">
import {inject} from "vue";
import {FormFieldIdKey} from "~/components/form-field.vue";

// Props
defineProps<{
  onChange?: (value: string) => void;
  placeholder?: string;
  type: "email" | "number" | "password" | "search" | "tel" | "text" | "url";
  value: string;
}>();

// Context
const id = inject(FormFieldIdKey, undefined);
</script>

<template>
  <div class="border-1 p-2 rounded-md centered-row">
    <slot name="leading" />

    <input
      class="bg-transparent outline-none w-full"
      :class="{
        'ml-2': $slots.leading !== undefined,
        'mr-2': $slots.trailing !== undefined,
      }"
      :id="id"
      :placeholder="placeholder"
      :type="type"
      :value="value"
      @input="onChange?.(($event.target as HTMLInputElement).value)"
    />

    <slot name="trailing" />
  </div>
</template>

// src/components/TextBox.tsx
/**
 * @fileoverview Text box component
 */

//Imports
import {JSXElement, Show, useContext, type Component} from "solid-js";
import {FormFieldIdContext} from "~/components/FormField";

interface TextBoxProps {
  leading?: JSXElement;
  onChange?: (value: string) => void;
  placeholder?: string;
  trailing?: JSXElement;
  type: "email" | "number" | "password" | "search" | "tel" | "text" | "url";
  value: string;
}

const TextBox: Component<TextBoxProps> = props => {
  const id = useContext(FormFieldIdContext);

  return (
    <div class="border-1 p-2 rounded-md centered-row">
      <Show when={props.leading !== undefined}>{props.leading}</Show>

      <input
        class="bg-transparent outline-none w-full"
        classList={{
          "ml-2": props.leading !== undefined,
          "mr-2": props.trailing !== undefined
        }}
        id={id}
        onChange={event => props.onChange?.(event.target.value)}
        placeholder={props.placeholder}
        type={props.type}
        value={props.value}
      />

      <Show when={props.trailing !== undefined}>{props.trailing}</Show>
    </div>
  );
};

export default TextBox;
